services:
  - type: web
    name: sdxl-lora-app
    env: python
    plan: starter  # or 'gpu' if paid
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
